/* This file was automatically generated by the typescript:generate command. */
interface PrescriptionModalHasDrugsModel {
  uuid: string;
  note: string;
  duration: number;
  durationType: string;
  standardDrug: StandardDrugModel;
  prescriptionModalHasDrugs: PrescriptionModalHasDrugs;
  locale: string;
}